### PR TITLE
Updating to a new JVM version and removing flags

### PR DESCRIPTION
**Pull request by paoliniluis**
Updating to Java 11 and also removing flags, seems to run way more stable and with less mem consumption than using Java 8 and flags

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
I don't think this should be moved to Java 17 before we're defaulting to that elsewhere too.

**Comment by paoliniluis** [comment]
https://github.com/metabase/metabase/issues/21264

**Comment by mehlah** [comment]
Meanwhile, since version 0.44 Java 11 is required and the `UseCGroupMemoryLimitForHeap` option doesn't exist anymore.

This can be reproduced on a default Heroku app deployed in the Heroku22 stack (latest stable)
(on Heroku20, the current default when using the deploy button or creating a new app, it doesn't load Java 11 by default anyway)

```
2022-08-04T19:58:10.901071+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport -Xmx300m -Xss512k -XX:CICompilerCount=2 -Dfile.encoding=UTF-8
2022-08-04T19:58:10.901311+00:00 app[web.1]: Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
2022-08-04T19:58:10.901963+00:00 app[web.1]: Error: Could not create the Java Virtual Machine.
2022-08-04T19:58:10.901970+00:00 app[web.1]: Error: A fatal exception has occurred. Program will exit.
```

Before making 17 the default, can't be 11 at least?

**Comment by codingjoe** [comment]
@flamber it seems the PR was downgraded to v11. I tested it and "it works on my machine". That machine being a heroku-22 image.

Right now, Heroku deploys won't work unless we upgrade the repo here to use JDK11.

**Review by camsaul — APPROVED** [review]

**Pull request merged**
