### PR TITLE
Jkutner buildpack approach

### PR DESCRIPTION
**Pull request by salsakran**
This keep this repo from becoming ginormous over time. It's already silly large, and we should figure out a way to remove the old binaries as well.

@tlrobinson Can you review this + https://github.com/metabase/metabase-buildpack ?

### CODE REVIEW

**Comment by tlrobinson** [comment]
Seems pretty reasonable.

I think we could/should combine the buildpack and deploy repos. There's no reason they can't be the same repo.

If for some reason we don't want to do that, at a minimum I *definitely* think we should move `bin/version` file to `metabase-deploy` so it's versioned along with `bin/start` and `app.json`.

Finally, just another reminder we really should be using HTTPS on downloads.metabase.com.

**Comment by tlrobinson** [comment]
I consolidated these 2 repos and did a bunch of cleanup and enhancement in https://github.com/metabase/metabase-heroku

It attempts to cache the jar (not sure that will make a difference) as well as verify the signed jar.

There's a script at `bin/update`that checks and updates with a new version. I've run it for all our previous releases (some of the older ones failed for some reason)

**Comment by salsakran** [comment]
Is the intention to see if that repo is the right course, and if so PR an equivalent set of changes against this repo, or to replace it entirely?

@tlrobinson I'd rather not have an entirely new repo for this. If we decide that "metabase-deploy" is vague, I'd rather just rename the repo so we get a redirect and don't break everything that points to it.

**Comment by tlrobinson** [comment]
I wanted to start with a fresh repo since this one more than 1GB now. I don't care too much about the name, but I do think `metabase-heroku` is a more appropriate name. I think we can rename this one then force push the new one.

**Comment by tlrobinson** [comment]
Also, regardless of how we do this (separate repo approach or mine, renaming or not) the upgrade path is going to be slightly annoying for 0.23 -> 0.24 or whenever we switch because existing apps will need to change their buildpacks.

It's a one liner they'll need to run, we'll just need to communicate it somehow. We might be able to set it up to throw an error if they haven't done it.

**Comment by tlrobinson** [comment]
@salsakran any opinions on how to proceed with this?

**Comment by salsakran** [comment]
@tlrobinson I'm thinking of merging this, and updating the release script. And then possibly do the switch you discussed.

**Comment by tlrobinson** [comment]
My version consolidates the buildpack and app repo, and various other improvements like caching and checking the jar signature

**Pull request merged**
